services:
    lucaszz_facebook_authentication.guzzle:
        class: GuzzleHttp\Client

    lucaszz_facebook_authentication.model.facebook_users:
        class: Lucaszz\FacebookAuthenticationBundle\Model\FacebookUsers
        arguments:
            - @fos_user.user_manager

    lucaszz_facebook_authentication.security.facebook_login_manager:
        class: Lucaszz\FacebookAuthenticationBundle\Security\FacebookLoginManager
        arguments:
            - @lucaszz_facebook_authentication.adapter.facebook_api
            - @lucaszz_facebook_authentication.model.facebook_users
            - @fos_user.security.login_manager
            - %fos_user.firewall_name%

    lucaszz_facebook_authentication.event_listener.facebook_listener:
        class: Lucaszz\FacebookAuthenticationBundle\EventListener\FacebookListener
        arguments:
             - @router.request_context
             - @lucaszz_facebook_authentication.security.facebook_login_manager
             - %lucaszz_facebook_authentication.config%
        tags:
             - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }

    lucaszz_facebook_authentication.adapter.facebook_api:
        class: Lucaszz\FacebookAuthenticationBundle\Adapter\GuzzleFacebookApi
        arguments:
             - @lucaszz_facebook_authentication.guzzle
