services:
    lucaszz_facebook_authentication.guzzle:
        class: GuzzleHttp\Client

    lucaszz_facebook_authentication.adapter.facebook_urls:
        class: Lucaszz\FacebookAuthenticationBundle\Adapter\FacebookUrls
        arguments:
             - @router.request_context
             - %lucaszz_facebook_authentication.config%

    lucaszz_facebook_authentication.adapter.facebook_api:
        class: Lucaszz\FacebookAuthenticationBundle\Adapter\GuzzleFacebookApi
        arguments:
             - @lucaszz_facebook_authentication.guzzle
             - @lucaszz_facebook_authentication.adapter.facebook_urls
