services:
    lucaszz_facebook_authentication.guzzle:
        class: GuzzleHttp\Client

    lucaszz_facebook_authentication.adapter.facebook_api: @lucaszz_facebook_authentication.adapter.facebook_api.guzzle

    lucaszz_facebook_authentication.adapter.facebook_api.guzzle:
        class: Lucaszz\FacebookAuthenticationBundle\Adapter\GuzzleFacebookApi
        arguments:
             - @lucaszz_facebook_authentication.guzzle

    lucaszz_facebook_authentication.model.facebook_users:
        class: Lucaszz\FacebookAuthenticationBundle\Model\FacebookUsers
        arguments:
            - @fos_user.user_manager

    lucaszz_facebook_authentication.security.facebook_login_manager:
        class: Lucaszz\FacebookAuthenticationBundle\Security\FacebookLoginManager
        arguments:
            - @lucaszz_facebook_authentication.adapter.facebook_api
            - @lucaszz_facebook_authentication.model.facebook_users
            - @fos_user.security.login_manager
            - %fos_user.firewall_name%

    lucaszz_facebook_authentication.security.facebook_listener:
        class: Lucaszz\FacebookAuthenticationBundle\Security\FacebookListener
        arguments:
             - @lucaszz_facebook_authentication.security.facebook_login_manager
             - @router.request_context
             - @security.context
             - @?
             - @?
             - ?
             - %lucaszz_facebook_authentication.config%